---
# tasks for find-ami
- ec2_ami_find :
    ami_tags   : "{{ base_ami.tags }}"
    region     : "{{ base_ami.region }}"
  register     : ami_id

- name: Get AMIs id
  set_fact: ami_id="{{ ami_id }}"
